""" 
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        freq_s = Counter(s)
        freq_t = Counter(t)
        for x,y in freq_t.most_common():
            if y!=freq_s[x]:
                return x
            